#!/bin/sh

# if we ever want to remove this script, install_name_tool can be used to replace the DYLD_LIBRARY_PATH hack
export DYLD_LIBRARY_PATH="${0%/*}"
	# same dir as the executable

set -- "$0"-bin "$@" -notexturenonpoweroftwo

case "`sw_vers -productVersion`" in
	# OSX Lion up to 10.7.2 has problems with SDL and running fullscreen, hence we force windowed mode
	10.7.[0-2])
		exec "$@" +vid_fullscreen 0
		;;
	# shell pattern for "10.6 and higher"
	10.[6-9]*|10.[1-5][0-9]*|1[1-9]*|[2-9]*)
		# no workaround needed on 10.6+
		exec "$@"
		;;
	*)
		# need to force a 32bit arch on 10.5 and below
		exec arch -arch i386 -arch ppc "$@"
		;;
esac
