#!/bin/env bash
cfg="font-cjk.cfg"
languages=$(awk '{ if (substr($1, 1, 2) != "zh" && substr($1, 1, 2) != "ja" && substr($1, 1, 2) != "ko") print $1 }' <"../xonotic-data.pk3dir/languages.txt")

printf "" >"$cfg"

cat >>"$cfg" <<EOF
// generated by make-cfg.sh, do not edit

// run before execing font cfg files (e.g. font-xolonium.cfg) and after switching language
// pick a correct cjk font variant by locale as a cvar \$font_cjk

// medium weight fits the game well
set _font_cjk_weight Medium

// jp as default variant for non-cjk languages
set _font_cjk_variant jp

EOF

for lang in $languages; do
    echo "alias _font_cjk_variant_${lang} _font_cjk_variant jp" >>"$cfg"
done

cat >>"$cfg" <<EOF

// variant by cjk languages
alias _font_cjk_variant_zh_CN _font_cjk_variant sc
alias _font_cjk_variant_zh_HK _font_cjk_variant hk
alias _font_cjk_variant_zh_TW _font_cjk_variant tc
alias _font_cjk_variant_ja_JP _font_cjk_variant jp
alias _font_cjk_variant_ko _font_cjk_variant kr

// pick a variant by current language
_font_cjk_variant_\${prvm_language}

// use this cvar in loadfont commands
set font_cjk fonts/NotoSansCJK\${_font_cjk_variant}-\${_font_cjk_weight}.otf

// clean up
unset _font_cjk_variant
unset _font_cjk_weight

EOF

for lang in $languages zh_CN zh_HK zh_TW ja_JP ko; do
    echo "unalias _font_cjk_variant_${lang}" >>"$cfg"
done

