#!/bin/sh

map=$1; shift
count=$1; shift
watchdog=$1; shift
dummy=$1; shift

# convert count to unary
count=`yes x | head -n "$count" | tr -cd x`

./all run \
	-nosound \
	+'locksession 0' \
	+'scr_screenshot_timestamp 0' \
	+'vid_fullscreen 0' \
	+'exec effects-ultimate.cfg' \
	"$@" \
	+'r_motionblur 0' \
	+'r_damageblur 0' \
	+'r_letterbox -1' \
	+'r_drawviewmodel 0' \
	+'crosshair 0' \
	+'sv_cheats 2' \
	+'set catchme "catchme_"' \
	+"alias catchme_$count \"quit\"" \
	+'alias NARF "sv_cmd nextframe cl_cmd nextframe $*"' \
	+'alias ZORT "god; noclip; NARF POIT"' \
	+'alias POIT "$catchme; set catchme \"${catchme}x\"; impulse 911; NARF TROZ"' \
	+'alias TROZ "screenshot; NARF POIT"' \
	+'alias cl_hook_gamestart_all "echo HOOKED; cmd join; defer 2 ZORT"' \
	+"defer \"$watchdog\" quit" \
	+"map \"$map\"" \
	+'timelimit 0' \
	+'fraglimit 0' \
	</dev/null
